[custom.all.idris2-coverage-core]
type = "local"
path = "../Idris2CoverageCore"
ipkg = "idris2-coverage-core.ipkg"

[custom.all.idris2-icwasm]
type = "local"
path = "../Idris2IcWasm"
ipkg = "idris2-icwasm.ipkg"

[custom.all.idris2-dfx-coverage]
type = "local"
path = "."
ipkg = "idris2-dfx-coverage.ipkg"

[install]
libs = ["idris2-coverage-core", "idris2-icwasm", "idris2-dfx-coverage"]
