// Auto-generated by RN.Scaffold (Idris2). Do not edit by hand.
// 1) FFI bridge installs global.__idrisRN and drives AppRegistry.
require('./idris-rn-shim.js');
// 2) Idris2-compiled bundle: running `main` calls __idrisRN.run, which
//    registers the React component named 'IdrisApp'.
require('./idris-bundle.js');