#!/usr/bin/env bash
# Auto-generated by RN.Scaffold (Idris2). Adds ios/ + android/ native shells.
# Idempotent-ish: re-running re-applies the Idris2-owned files.
set -euo pipefail
APPDIR="$(cd "$(dirname "$0")" && pwd)"
APPNAME="IdrisApp"

# 1) Materialise native shells with the official community template into a temp
#    dir, then move ios/ and android/ next to our Idris2-owned files.
TMP="$(mktemp -d)"
npx --yes @react-native-community/cli@latest init "$APPNAME" \
  --directory "$TMP/$APPNAME" --skip-install --version 0.73.6
cp -R "$TMP/$APPNAME/ios"     "$APPDIR/ios"
cp -R "$TMP/$APPNAME/android" "$APPDIR/android"
rm -rf "$TMP"

# 2) Re-assert the Idris2-owned entry + bundle (the template ships its own
#    index.js / App.tsx which we replace with our generated wiring).
#    index.js, package.json, app.json, metro.config.js, babel.config.js were
#    already written by `writeScaffold`; idris-rn-shim.js and idris-bundle.js
#    are copied in by build.sh. Nothing else to do here — the native projects
#    read index.js at runtime via Metro.

echo "Native shells ready. Next:"
echo "  cd '$APPDIR' && npm install"
echo "  # Android (device on USB, USB debugging ON):"
echo "  npx react-native run-android"
echo "  # iOS (device on USB, full Xcode + CocoaPods required):"
echo "  (cd ios && pod install) && npx react-native run-ios"