[custom.all.idris2-coverage-core]
type = "local"
path = "../Idris2CoverageCore"
ipkg = "idris2-coverage-core.ipkg"

[custom.all.idris2-evm]
type = "local"
path = "../Idris2Evm"
ipkg = "idris2-evm.ipkg"
