# idris2-subcontract pack.toml
# Subcontract framework depends on idris2-evm

[custom.all.idris2-evm]
type   = "local"
path   = "../Idris2Evm"
ipkg   = "idris2-evm.ipkg"

[custom.all.idris2-subcontract]
type   = "local"
path   = "."
ipkg   = "idris2-subcontract.ipkg"
