-- ===================================================================
-- AUTO-GENERATED by idris2-evm-coverage
-- This wrapper imports all modules and calls all exported IO functions
-- to enable comprehensive coverage analysis via --dumpcases.
-- ===================================================================

module DumpcasesWrapper

import Main

main : IO ()
main = do
  -- Calling all exported IO functions to include them in dumpcases analysis
  _ <- Main.runCovered

  pure ()